export const OUTPUT_CONTAINER_API_CHANNEL_NAME = 'CASTCHAIN_PLUGIN_HANDLE'

export enum OUTPUT_CONTAINER_API_ENTRIES {
  INIT_CHECK,
  LIST_PLUGIN,
  CREATE_PLUGIN,
  DESTROY_PLUGIN
}

export enum OUTPUT_API_ENTRIES {
  GET_NAME,
  START_PUBLISH,
  STOP_PUBLISH
}
