export const CONTAINER_API_CHANNEL_NAME = 'CASTCHAIN_PLUGIN_HANDLE'

export enum CONTAINER_API_ENTRIES {
  INIT_CHECK,
  LIST_PLUGIN,
  CREATE_PLUGIN,
  DESTROY_PLUGIN
}

export enum SOURCE_API_ENTRIES {
  GET_NAME,
  START_PUBLISH,
  STOP_PUBLISH
  // DATA_ARRIVE, -> START_PUBLISHでハンドル返す？
  // ERROR_OCCURS ->
}

// NEW

export enum MOCK_SOURCE_API_ENTRIES {
  UPDATE_CONFIG
}
